# Generated by Django 3.2.8 on 2021-10-29 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('image_1', models.ImageField(default='defualt-image.jpg', upload_to='Projects_Images')),
                ('image_2', models.ImageField(default='defualt-image.jpg', upload_to='Projects_Images')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('frontEnd_techniques', models.CharField(max_length=300)),
                ('backEnd_techniques', models.CharField(max_length=300)),
            ],
        ),
    ]
