# Generated by Django 3.2.8 on 2021-10-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211029_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecievedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderName', models.CharField(max_length=100)),
                ('senderEmail', models.EmailField(max_length=100)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
