# Generated by Django 3.2.8 on 2021-10-29 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_recievedemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecievedEmail',
        ),
    ]
