# Generated by Django 3.2.8 on 2021-10-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_delete_recievedemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='other_techniques',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='backEnd_techniques',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='frontEnd_techniques',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
